version: '3.9'

services:
  films:
    build: films
    ports:
      - "8081:8080"
    depends_on:
      - films-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://films-db:5432/films
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123

  payments:
    build: payments
    ports:
      - "8082:8080"
    depends_on:
      - payments-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-db:5432/payments
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123

  films-db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=films
    volumes:
      - films-db-data:/var/lib/postgresql/data

  payments-db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=payments
    volumes:
      - payments-db-data:/var/lib/postgresql/data

volumes:
  films-db-data:
  payments-db-data:
