apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  SPRING_DATASOURCE_URL: <base64-encoded-url>
  SPRING_DATASOURCE_USERNAME: <base64-encoded-username>
  SPRING_DATASOURCE_PASSWORD: <base64-encoded-password>
  PAYMENT_SERVICE_ADDR: <base64-encoded-payment-service-addr>