apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.payments.name }}
  labels:
    app: {{ .Values.app.name }}
    component: {{ .Values.services.payments.name }}
spec:
  type: {{ .Values.services.payments.service.type }}
  ports:
    - port: {{ .Values.services.payments.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.payments.name }}
