AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create an Amazon ECR repository
Parameters:
  ServiceName:
    Description: The name of the service
    Type: String
    Default: 'demo'
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub 'demo-repo-${ServiceName}'
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'

Outputs:
  RepositoryUrl:
    Description: The URL of the created ECR repository
    Value: !Join ['', ['https://', !Ref AWS::AccountId, '.dkr.ecr.', !Ref AWS::Region, '.amazonaws.com/', !Ref ECRRepository]]
