services:
  films:
    env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://films-db:5432/films
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: 123
    - name: PAYMENT_SERVICE_ADDR
      value: payments:8080
  payments:
    env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://payments-db:5432/payments
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: 123

ingress:
  enabled: true
  hosts:
    - host: staging.tdk-microservices-demo.synthesized.io
      http:
        paths:
        - path: /api/v1/films
          pathType: ImplementationSpecific
          backend:
            service:
              name: films-api
              port:
                number: 80
  tls: []
