transformation_configs:
  payments:
    default_config:
      mode: "MASKING"
    tables:
      - table_name_with_schema: "public.inventory"
        transformations:
          - columns: [ "film_id" ]
            params:
              type: "passthrough"
      - table_name_with_schema: "public.flyway_schema_history"
        mode: "KEEP"

  films:
    default_config:
      mode: "MASKING"
    tables:
      - table_name_with_schema: "public.films"
        transformations:
          - columns: [ "film_id" ]
            params:
              type: "passthrough"
      - table_name_with_schema: "public.flyway_schema_history"
        mode: "KEEP"

data_source_mapping:
  payments:
    source: "payments_prod"
    targets:
      - "payments_staging"
  films:
    source: "films_prod"
    targets:
      - "films_staging"