transformation_configs:
  payments:
    default_config:
      mode: "MASKING"
    tables:
      - table_name_with_schema: "public.inventory"
        transformations:
          - columns: [ "film_id" ]
            params:
              type: "passthrough"
      - table_name_with_schema: "public.flyway_schema_history"
        mode: "KEEP"
    safety_mode: "RELAXED"
    cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
    schema_creation_mode: "DO_NOT_CREATE"
    table_truncation_mode: "TRUNCATE"

  films:
    default_config:
      mode: "MASKING"
    tables:
      - table_name_with_schema: "public.film"
        transformations:
          - columns: [ "film_id" ]
            params:
              type: "passthrough"
      - table_name_with_schema: "public.flyway_schema_history"
        mode: "KEEP"
    safety_mode: "RELAXED"
    cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
    schema_creation_mode: "DO_NOT_CREATE"
    table_truncation_mode: "TRUNCATE"

data_source_mapping:
  payments:
    source: "payments_prod"
    targets:
      - "payments_staging"
  films:
    source: "films_prod"
    targets:
      - "films_staging"