# Default values for tdk-microservices-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

apps:
  films:
    service:
      port: 80
      protocol: TCP
      type: ClusterIP
    image:
      repository: films
      pullPolicy: IfNotPresent
      tag: ""
      containerPort: 8080
  payments:
    service:
      port: 80
      protocol: TCP
      type: ClusterIP
    image:
      repository: payments
      pullPolicy: IfNotPresent
      tag: ""
      containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
