apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://rds.example.com:5432/payments"
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
