ingress:
  enabled: true
  hosts:
    - host: tdk-microservices-demo.example.com
      http:
        paths:
        - path: /api/v1/films
          pathType: ImplementationSpecific
          backend:
            service:
              name: films-api
              port:
                number: 80
  tls: []
