name: CI/CD

on:
  push:
    branches:
      - heml-charts
      - ci-cd

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: 248441125472
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
  STAGING_CLUSTER_NAME: demo-eks-cluster-staging
  PROD_CLUSTER_NAME: demo-eks-cluster-prod

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::8})" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push films Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/demo-repo-films:${{ env.SHORT_SHA }}
          file: Dockerfile.films

      - name: Build and push payments Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/demo-repo-payments:${{ env.SHORT_SHA }}
          file: Dockerfile.payments

      - name: Set up Kubernetes environment
        uses: azure/setup-kubectl@v1

      - name: Update kubeconfig for staging
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.STAGING_CLUSTER_NAME }} --kubeconfig ${{ env.KUBECONFIG }}

      - name: Deploy to staging
        run: |
          kubectl config use-context arn:aws:eks:${{ env.AWS_REGION }}:${{ env.AWS_ACCOUNT_ID }}:cluster/${{ env.STAGING_CLUSTER_NAME }}
          helm upgrade tdk-microservices-demo ./infrastructure/helm/charts/tdk-microservices-demo \
            --values ./infrastructure/helm/environments/staging/values-staging.yaml \
            --namespace tdk-microservices-demo \
            --set services.films.image.tag=${{ env.SHORT_SHA }} \
            --set services.payments.image.tag=${{ env.SHORT_SHA }}

      - name: Run tests
        run: |
          curl -sfL "http://staging.tdk-microservices-demo.synthesized.io/api/v1/films/1" || exit 1

      - name: Rollback on test failure
        if: ${{ failure() }}
        run: |
          helm rollback tdk-microservices-demo --namespace tdk-microservices-demo
          exit 1

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build-and-deploy-staging

    steps:
      - name: Update kubeconfig for prod
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.PROD_CLUSTER_NAME }} --kubeconfig ${{ env.KUBECONFIG }}

      - name: Deploy to production
        if: github.event_name == 'workflow_dispatch'
        run: |
          kubectl config use-context arn:aws:eks:${{ env.AWS_REGION }}:${{ env.AWS_ACCOUNT_ID }}:cluster/${{ env.PROD_CLUSTER_NAME }}
          helm upgrade tdk-microservices-demo ./infrastructure/helm/charts/tdk-microservices-demo \
            --values ./infrastructure/helm/environments/production/values-prod.yaml \
            --namespace tdk-microservices-demo \
            --set services.films.image.tag=${{ env.SHORT_SHA }} \
            --set services.payments.image.tag=${{ env.SHORT_SHA }}
